# Change these first
owner: quicoto # Your GitHub organization or username, where this repository lives
repo: mastodon-uptime # The name of this repository

sites:
  - name: API Health
    url: https://ricard.social/api/v1/streaming/health  
  - name: Mastodon FE
    url: https://ricard.social/

status-website:
  baseUrl: /mastodon-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Ricard Social uptime
  navbar:
    - title: Status
      href: /mastodon-uptime/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

assignees:
  - quicoto

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
